version: "3"
services:
  web:
    build: .
    command: npm run watch
    volumes:
      - .:/app
    ports:
      - "5000:8080"
    links:
      - db
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"